### ISSUE TITLE
PyPI does not like direct dependency in pyproject.toml

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/rail_flexzboost#12]
In a previous commit I moved the FlexCode dependency on the CMU fork from requirements.txt to pyproject.toml.  When the GitHub action tries to upload a tagged version with this dependency we get an error
```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         Invalid value for requires_dist. Error: Can't have direct dependency:  
         'FlexCode @ git+https://github.com/lee-group-cmu/FlexCode'
```
i.e. PyPI won't let us depend on a forked GH repo rather than one on PyPI.  We'll need to move this dependency out of pyproject.toml until we get a forked version on Github somewhere, plus update the install instructions in README.md to tell the user that they'll need to do a 
```
pip install FlexCode @ git+https://github.com/lee-group-cmu/FlexCode
```
in order to grab the dependency before they install rail_flexzboost

**Comment by drewoldag** [comment]
This issue was addressed by this PR #15
