### ISSUE TITLE
pyproject.toml not grabbing CMU FlexCode from requirements.txt

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/rail_flexzboost#8]
It looks like doing a  `pip install pz-rail-flexcode` does not actually grab the requirements.txt with the CMU fork of FlexCode.

Temporary work around is to do a pip install -r requirements.txt if you git cloned the repo, or do a 
`pip install git+https://github.com/lee-group-cmu/FlexCode` to grab FlexCode 0.2.

Need to figure out how to get the new pyproject.toml to properly install requirements from GitHub that are not yet on PyPI

**Comment by drewoldag** [comment]
This issue has been addressed by this PR #15
